---
- name: Deploy Docker Nginx App
  hosts: web
  become: yes
  gather_facts: no

  tasks:

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Create project directory
      file:
        path: /home/ec2-user/network-project
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Copy app folder to EC2
      copy:
        src: ../app/
        dest: /home/ec2-user/network-project/app/
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Stop old container if exists
      command: docker stop network-container
      ignore_errors: yes

    - name: Remove old container if exists
      command: docker rm network-container
      ignore_errors: yes

    - name: Build Docker image (no cache)
      command: docker build --no-cache -t network-app .
      args:
        chdir: /home/ec2-user/network-project/app/

    - name: Run Docker container
      command: docker run -d -p 80:80 --name network-container network-app
