name: DevOps CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  build-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform Format Check
        working-directory: ./terraform
        run: terraform fmt -check

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Ansible Syntax Check
        run: |
          ansible-playbook ansible/nginx-playbook.yml --syntax-check

      - name: Validate Dockerfile
        run: |
          if [ -f app/Dockerfile ]; then
            echo "Dockerfile exists"
          else
            echo "Dockerfile missing"
            exit 1
          fi

  deploy:
    needs: build-and-validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            sudo yum install -y git

            sudo yum install -y docker
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker ec2-user

            mkdir -p /home/ec2-user/network-project
            cd /home/ec2-user/network-project
            if [ ! -d .git ]; then
              git clone https://github.com/anin27/network-project.git .
            else
              git pull origin main
            fi

            cd app
            sudo docker stop network-container || true
            sudo docker rm network-container || true
            sudo docker build --no-cache -t network-app .
            sudo docker run -d -p 80:80 --name network-container network-app
          EOF
